### ISSUE TITLE
can you offer the demo files 

### ISSUE THREAD

**Issue by damozhiying** [mushketyk/flink-examples#1]
please offer the demo files such as 
/Users/ivanmushketyk/Flink/ml-latest-small/movies.csv
/Users/ivanmushketyk/Flink/ml-latest-small/ratings.csv

**Comment by mushketyk** [comment]
Hi @damozhiying 

Most demos are using MovieLens dataset: https://grouplens.org/datasets/movielens/ 
You can download a small (100K ratings) or a full dataset (20M ratings).
